
# task 1
print ("Hello World")

# task 2
print ("Hello Kurt")

# task 3
Celcius = 38.4
Fahrenheit = Celcius * 1.8 + 32
print ("The Temperature in Yorkshire is", Celcius, "C or", Fahrenheit, "F")

# task 4
BattingAverage = 48426 / (1014 -162 )
print (" Batting Average is ", BattingAverage )

# task 5

LabSize=24
Group1S= (113 % LabSize)
Group2S= (175 % LabSize)
Group3S= (12 % LabSize)
Group1F=(113 - Group1S)
Group2F= (175 - Group2S)
Group3F= (12 - Group3S)

Group1G= (Group1F / 24)
Group2G= (Group2F / 24)
Group3G= (Group3F / 24)



print ("Group 1 has",Group1G,"full groups and ", Group1S, "remainding students")
print ("Group 2 has",Group2G,"full groups and ", Group2S, "remainding students")
print ("Group 3 has",Group3G,"full groups and ", Group3S, "remainding students")
